### PR TITLE
Create ma-MA

### PR DESCRIPTION
**Pull request by ykl111**
Indievelo Malay translation

### CODE REVIEW

**Comment by George-Gilbert** [comment]
Hi - can I just check that you intentionally closed / deleted this?  If you instead want to see it published and available in-game for you to use, please let me know and I will add it for you!

Also, if you do want it published, please let me know your name, I can add you to the in-game credits.

**Comment by ykl111** [comment]
Hi George,Thanks. Yes, wanted to get this published.

Regards
Kev Yee

 
 
  On Tue, 4 Jun 2024 at 4:58 am, ***@***.***> wrote:   


Hi - can I just check that you intentionally closed / deleted this? If you instead want to see it published and available in-game for you to use, please let me know and I will add it for you!

Also, if you do want it published, please let me know your name, I can add you to the in-game credits.

**Comment by indieVelo** [comment]
That's great - thank you.   This is now live in-game!

**Comment by ykl111** [comment]
Thanks George. Looking good.
I would like improve it further by shortening key words. Will update you again tomorrow.

Regards
Kev Yee
 
 
  On Tue, 4 Jun 2024 at 4:21 pm, ***@***.***> wrote:   


That's great - thank you. This is now live in-game!

**Comment by ykl111** [comment]
Committed an updated version for your review.
I looked at existing IV Interface, clean and slick look. So I reduced the number of words to align to original look and feel. 

Regards
Kok Leong
97976170 
 
  On Tue, 4 Jun 2024 at 7:01 pm, ***@***.***> wrote:   Thanks George. Looking good.
I would like improve it further by shortening key words. Will update you again tomorrow.

Regards
Kev Yee
 
 
  On Tue, 4 Jun 2024 at 4:21 pm, ***@***.***> wrote:   


That's great - thank you. This is now live in-game!

**Comment by indieVelo** [comment]
Hi - I can't see the changes you've made (probably because they are just on your computer).  Can you please follow the instructions on https://github.com/indieVelo/translations and I'll then be able to add them?

**Comment by ykl111** [comment]
thanks. let me know if you can see it.

**Pull request closed without merging**
